#!/bin/bash

### Git Shorthands Usage:help
#
# Some shorthands for managing git repositories.
#
###

#% bundle help/info.txt

if [[ "$*" =~ --help ]]; then
	cat help/info.txt
	exit 0
fi

#% include autohelp bashout askuser

ADDFILE=
COMMIT=
ACTION=
CURBRANCH="$(git branch|grep -P '(?<=\* ).+' -o)"
branchpat='^[a-zA-Z0-9_-]+$'

function switchchangestobranch {
	local dash="$-"; set -e

	gotobranch=$(uchoose "Which branch should ALL tracked and uncommitted changes be moved to?" "$(git branch|egrep -v '^\* ')")
	git stash
	git checkout "$gotobranch"
	git stash apply
	CURBRANCH="$(git branch|grep -P '(?<=\* ).+' -o)"

	if [[ ! $dash =~ e ]]; then set +e; fi
}

function switchbranch {
	local newbranch=$1; shift

	if ! (git branch|grep "$newbranch" >/dev/null); then
		uconfirm "'$newbranch' does not exits. Create it?" && git branch "$newbranch"
	fi
	git checkout "$newbranch"
	CURBRANCH="$(git branch|grep -P '(?<=\* ).+' -o)"
}

debuge "Rudimentary check that we are in a safe state"

if [[ -n "$(git status | egrep 'unmerged|both modified' | sed -r 's/^(\s.+)$/[0;31m\1[0m/')" ]]; then
	warne "Conflicts identified."
	faile "gdiff cannot operate on this state."
fi

# ======

if [[ -z "$@" ]]; then
	git fetch

	if [[ "$CURBRANCH" = master ]]; then
		warne "${CBRED}\n\tYou are currently on master\n"
		uconfirm "Move changes to a different branch?" && switchchangestobranch
	fi

	git status
	exit 0
fi

# need to also consider - merge and rollback

while [[ -n "$@" ]]; do
	ARG=$1
	shift

	case "$ARG" in
	-b|--branch)
		switchbranch "$1"; shift
		;;
	-r|--rebranch)
		switchchangestobranch "$1"; shift
		;;
	-m)
		ACTION=commit
		COMMIT="$*" # get the rest of the arguments as commit message
		break
		;;
	-a)
		ACTION=add
		;;
	-s|--push)
		infoe "git push origin $CURBRANCH"
		git push origin "$CURBRANCH"
		exit $?
		;;
	-l|--pull)
		infoe "git pull origin $CURBRANCH"
		git pull origin "$CURBRANCH"
		exit $?
		;;
	-u|--rebase)
		infoe "git rebase $CURBRANCH"
		git rebase "$1"; shift
		exit $?
		;;
	*)
		if [[ -e "$ARG" ]]; then
			ADDFILE="$ADDFILE $ARG"
		else
			faile "No such file [$ARG]" 2
		fi
		;;
	esac
done

if [[ "$ACTION" = commit ]]; then
	git add $ADDFILE
	if [[ -z "$COMMIT" ]]; then
		git commit
	else
		git commit -m "$COMMIT"
	fi
elif [[ "$ACTION" = add ]]; then
	git add $ADDFILE
else
	for cfile in $ADDFILE; do
		if [[ -d "$cfile" ]]; then
			echo "Skipping directory [$cfile]"
			continue
		fi
		git diff "$cfile" | sed -r -e 's//^[/g' -e "s/^(-.*)$/${CRED}\1${CDEF}/" -e "s/^(\+.*)$/${CGRN}\1${CDEF}/" -e "s/^(@@.+)$/${CBLU}\1${CDEF}/" | less -R
	done
fi
