#!/bin/bash

## -------- optional - add signal trap
## 'trap' COMMAND signal

#trap 'exit' SIGINT

## -------- Define colours

CDEF='[0m'
CRED='[0;31m' # Regular
CGRN='[0;32m'
CYEL='[0;33m'
CBLU='[0;34m'
CRDB='[1;31m' # Bold (if supported)
CGNB='[1;32m'
CYLB='[1;33m'
CBUB='[1;34m'
CRDU='[4;31m' # Underline (if supported)
CGNU='[4;32m'
CYLU='[4;33m'
CBUU='[4;34m'
CRDH='[0;41m' # Highlight
CGNH='[0;42m'
CYLH='[0;43m'
CBUH='[0;44m'

## -------- Define help routine

function printhelp { # MODIFY AS APPROPRIATE, including copyright and license
cat <<EOHELP

	${CBUB}Program Name${CDEF}

${CBUB}copyright:   $CDEF (C) DATE AUTHOR
${CBUB}license:     $CYEL GNU General Public License version 3
${CBUB}license url: $CBLU https://www.gnu.org/licenses/gpl-3.0.html${CDEF}

Usage:

	${CBLU}$0 ${CYEL}OPTIONS${CDEF}

${CYEL}option${CDEF}

Comment

EOHELP
}

helppat='--help|-h'
[[ "$@" =~ $helppat ]] && {
	printhelp
	exit
}

## -------- Add tests for unset variables here

## -------- Set error handling

set -euo pipefail

## -------- Define script-wide variables

# Used in arg parsing, further below
FLAGOPT=

## -------- parse arguments

for arg in "$@"; do
	case "$arg" in
		--flag=*)
			FLAGOPT=${arg#--flag=}
			;;
		*)
			echo "Handled general argument ${CGRN}$arg${CDEF}"
			;;
	esac
done

## ++++++ Add main now +++++
