#! /bin/bash

if [[ "x$UID" != 'x0' ]]; then
	echo "You are not root."
	exit 1
fi

bindir="/usr/local/bin"
ytdlurl="https://yt-dl.org/downloads/latest/youtube-dl"
ytdlbin="$bindir/youtube-dl"
ytsongexe="$bindir/ytsong"

echo "Downloading YouTube Downloader from $ytdlurl ..."

wget -O "$ytdlbin" "$ytdlurl"

chmod a+rx "$ytdlbin"

if [[ ! -e "$ytsongexe" ]]; then
	cat <<EOSCRIPT > "$ytsongexe"
youtube-dl -x --audio-format vorbis $1
EOSCRIPT
else
	echo "INFO : $ytsongexe already exists; not creating."
fi


cat <<EOF

Successfully installed. Run [ youtube-dl -U ] to check for and install updates.

Run [ youtube-dl --help ] for a list of options.

A special script $ytsongexe should also be available to download and convert to Ogg/Vorbis audio.

Any issues, run the command again with the --verbose optiion added, and send reports to
  https://github.com/rg3/youtube-dl/issues/

EOF

