syntax on

" Read 'vim: ' commands in the first and last 5 lines of a file
" http://vim.wikia.com/wiki/Modeline_magic
set modeline
set modelines=5

" --- Not yet working:
" Enable filetype-based indentation
" http://vim.wikia.com/wiki/Indenting_source_code
" set indentexpr
" filetype indent on

set autoindent
set formatoptions=tcqr

" Lin / col number
set ruler

" Set a status bar ...?
set laststatus=2
set hlsearch

colorscheme koehler

" Confirm quit when multiple buffers are open
set confirm

" from http://vim.wikia.com/wiki/Converting_tabs_to_spaces
set tabstop=4
set shiftwidth=4
set expandtab
autocmd FileType yaml set tabstop=2|set shiftwidth=2|set expandtab
autocmd FileType html set tabstop=2|set shiftwidth=2|set expandtab

" In absence of powershell syntax profile, use perl (eck!)
autocmd BufNewFile,BufRead *.ps1 set syntax=perl


" Treat .vue files like .html
" http://vim.wikia.com/wiki/Forcing_Syntax_Coloring_for_files_with_odd_extensions
autocmd BufNewFile,BufRead *.vue set syntax=html

" Turn off bracketed paste
" https://vimhelp.appspot.com/term.txt.html#xterm-bracketed-paste
set t_BE=
