#!/bin/bash

### Inclusion Directives Usage:help
#
# You can add extra inclusion directives as follows:
#
# When inserted at the start of a line or title, assigns attributes to the element.
#
# 	### ${a|style="color: blue;" id="builds}$ How to perform builds
#
# Insert raw data - some arkdown processors will see opening tags as a sign to temporarily stop processing.
# This allows inserting raw tags without being affected by this.
#
# 	${raw|<div>}$
#
# Insert a javascript file ad a "script" element
#
# 	${js|path/to/js/file}$
#
# Insert a CSS file as a "<stye>" element
#
# 	${css|path/to/style/file}$
#
# Insert the raw contents of a file [still to be implemented]
#
# 	${i|path/to/extarnal/file.html}$
#
###/doc

function processinserts {
	if [[ ! -f "$1" ]]; then
		faile "No such file [$1]"
	else
		debuge "Processing inclusions on $1"
		sed -r -e 's/>\s*\$\{a\|(.+?)\}\$\s*/ \1 >/' \
		       -e 's/\$\{raw\|(.+?)\}\$/\1/' \
		       -e 's/\$\{js\|(.+?)\}\$/<script src="\1"><\/script> /' \
		       -e 's/\$\{css\|(.+?)\}\$/<style src="\1"><\/style> /' \
		       "$1" -i
	fi
}
