#!/bin/bash

### dl Usage:help
# Run a download on the command line
#
# Running the command again allows you to add a new file to the chain
# so you do not have to wait for the previous one to finish, nor run
# the downloads concurrently.
###/doc

set -u

#%include bashout autohelp

if [[ -z "$*" ]]; then
	out:fail "Specify a download file"
fi

listfile="$1" ; shift

if [[ -z "$*" ]]; then

	if [[ ! -f "$listfile" ]]; then
		out:fail "$listfile is not a file"
	fi

	cp "$listfile" "$listfile.save"

	out:info "You can add new URLs to the list by running"
	out:info "    $0 $listfile \$URL ..."
else
	while [[ -n "$*" ]]; do
		echo "$1" >> "$listfile" || out:fail "Could not write to $listfile"
		echo "$1" >> "$listfile.save" || out:fail "Could not write to $listfile.save"
		shift
	done
	exit
fi


while [[ $(head "$listfile"|wc -l) -gt 0 ]]; do
	url=$(head "$listfile" -n 1)
	out:info "Getting $url"
	if ! wget "$url"; then
		# save url for further processing
		out:warn Failed
		echo "$url" >> "$listfile.failed"
	fi
	# decapitate
	sed "2,$(wc -l < "$listfile") p" -n $listfile > "$listfile.tmp" || out:fail "Cannot write temp"
	cat "$listfile.tmp" > "$listfile" || out:fail "Cannot truncate list"
	rm "$listfile.tmp" || out:warn "Could not remove temp"
	out:info "debug sleep" && sleep 5
done

cp "$listfile.save" "$listfile" && rm "$listfile.save"
out:info "All contents of "$listfile" have been processed."
