#!/bin/bash

set -u

### Move Audio Input Usage:help
#
# Run without arguments to list sinks and running applications
#
# Run as
#
# 	mvaudio TGTINPUT TGTSINK
#
# to move the target input to the target sink
#
# Run as
#
# 	mvaudio TGTSINK
#
# to set the default output channel, and move all audio to
# the specified channel.
#
###/doc

#%include autohelp bashout

if [[ -z "$*" ]]; then
	infoe Available Inputs
	pacmd list-sink-inputs|grep -P 'index:|client:|application.process.binary'

	infoe Available Sinks
	pacmd list-sinks|grep -P 'index:|name:'
else
	TGTINPUT="$1"; shift

	if [[ -n "$*" ]]; then
		TGTSINK="$1"; shift
		pacmd move-sink-input "$TGTINPUT" "$TGTSINK"
	else
		TGTSINK="$TGTINPUT"
		pacmd set-default-sink "$TGTINPUT"

		inputs=$(pacmd list-sink-inputs|grep 'index:'|sed -r 's/\s*index:\s*//'|xargs echo)
		for TGTINPUTx in $inputs
		do
			pacmd move-sink-input "$TGTINPUTx" "$TGTSINK"
		done
	fi
fi
