#!/usr/bin/env bash

### Move Audio Input Usage:help
#
# Run without arguments to list sinks and running applications
#
# Run as
#
#     mvaudio TGTINPUT TGTSINK
#
# to move the target input to the target sink.
#
#
#
# Run as
#
#     mvaudio TGTSINK
#
# to set the default output channel, and move all audio to
# the specified channel.
#
#
#
# Run as
#
#     mvaudio
#
# to restart the pulseaudio server (sound card detection problems, for example)
#
###/doc

#%include std/safe.sh
#%include std/autohelp.sh
#%include std/out.sh

if [[ -z "$*" ]]; then
    out:info "Available Inputs"
    pacmd list-sink-inputs|grep -P 'index:|client:|application.process.binary'

    out:info "Available Sinks"
    pacmd list-sinks|grep -P 'index:|name:'
elif [[ "$1" = restart ]]; then
    pulseaudio -k
    pulseaudio --start
else
    TGTINPUT="$1"; shift

    if [[ -n "$*" ]]; then
        TGTSINK="$1"; shift
        pacmd move-sink-input "$TGTINPUT" "$TGTSINK"
    else
        TGTSINK="$TGTINPUT"
        pacmd set-default-sink "$TGTINPUT"

        IFS=$'\n' inputs=($(pacmd list-sink-inputs|grep 'index:'|sed -r 's/\s*index:\s*//') )
        for TGTINPUTx in "${inputs[@]}"; do
            pacmd move-sink-input "$TGTINPUTx" "$TGTSINK"
        done
    fi
fi
