#!/bin/bash

### pow Usage:help
# Simply display power stats
#
# Usage
# =====
#
# 	pow
#
# No options.
###/doc

#%include autohelp bashout

debuge "Getting Battery information for \`upower -i $(upower -e | grep 'BAT')\`"

upower -i $(upower -e | grep 'BAT') | grep -E "state|to\ full|percentage|time to"
