#!/bin/bash

### wget with user agent header Usage:help
#
# wgeta <normal wget arguments>
#
###/doc

#%include autohelp.sh

if [[ -z "$*" ]]; then
	printhelp
	wget # also print wget help
	exit
fi

wget --header="User-Agent: User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" "$@"
