#!/bin/bash

### wifi Usage:help
#
# Some simple wifi controls wrapping around nmcli
#
# USAGE
# =====
#
# 	nmcli [ list | start | stop | restart | connect ACCESSPOINT [PASSWORD] | forget ACCESSPOINT ]
#
# list
# 	Lists available access points
#
# start
# 	Activates the wifi device
#
# stop
# 	Stop the wifi device
#
# restart
# 	Restart the wifi device
#
# connect ACCESSPOINT [PASSWORD]
# 	Connect to the given access point, optionally providing a password
# 	If the password is provided, it is saved for future use.
# 	If the password is not provided, but a saved password exists, that saved password is used.
#
# forget ACCESSPOINT
# 	Forget the access point and password
#
###/doc

#%include bashout autohelp

SEP=''

if [[ -z "$(which nmcli)" ]]; then
	faile 'Required program `nmcli` not found.'
fi

if [[ -z "$*" ]]; then
	infoe "Raw wifi status\n"
	infoe "$(nmcli connection show --active | grep wireless)\n"
	exit
fi

WIFICMD="$1" ; shift

function newconn {
	WIFI_AP="$1"; shift
	WIFI_PW="$1"; shift

	infoe "Trying to establish new connection ..."

	if [[ -n "$WIFI_PW" ]]; then
		nmcli device wifi connect "$WIFI_AP" password "$WIFI_PW" ; RES=$?
	else
		nmcli device wifi connect "$WIFI_AP" ; RES="$?"
	fi

	return "$RES"
}

function oldconn {
	WIFI_AP="$1"; shift
	infoe "Trying old connections ..."

	nmcli connection up "$WIFI_AP" ; RES=$?

	return "$RES"
}

case "$WIFICMD" in
	restart)
		debuge Deactivating wifi
		nmcli radio wifi off

		debuge Re-activating wifi
		nmcli radio wifi on

		infoe Done.
		;;
	stop)
		debuge Deactivating wifi
		nmcli radio wifi off
		infoe Done.
		;;
	start)
		debuge Re-activating wifi
		nmcli radio wifi on
		infoe Done.
		;;
	connect)
		nmcli device wifi rescan
		WIFI_AP="$1"; shift
		WIFI_PW="$1"; shift

		if [[ -z  "$WIFI_AP" ]]; then
			printhelp
			exit
		fi

		oldconn "$WIFI_AP" || newconn "$WIFI_AP" "$WIFI_PW"
		;;
	forget)
		WIFI_AP="$1"; shift
		nmcli connection delete "$WIFI_AP" && {
			infoe Done.
		}
		;;
	list)
		nmcli device wifi rescan
		nmcli device wifi list
		;;
	old)
		WIFI_AP="$1" ; shift
		if [[ -z "$WIFI_AP" ]]; then
			nmcli connection show|grep wireless
		else
			nmcli connection show "$WIFI_AP"|grep wireless
		fi
		;;
	*)
		faile "Invalid command $WIFICMD"
		;;
esac
