#!/bin/bash

### wifi Usage:help
#
# Some simple wifi controls wrapping around nmcli
#
# USAGE
# =====
#
# 	nmcli [ list | start | stop | restart | connect ACCESSPOINT [PASSWORD] | forget ACCESSPOINT ]
#
# list
# 	Lists available access points
#
# start
# 	Activates the wifi device
#
# stop
# 	Stop the wifi device
#
# restart
# 	Restart the wifi device
#
# connect ACCESSPOINT [PASSWORD]
# 	Connect to the given access point, optionally providing a password
# 	If the password is provided, it is saved for future use.
# 	If the password is not provided, but a saved password exists, that saved password is used.
#
# forget ACCESSPOINT
# 	Forget the access point password
#
###/doc

#%include bashout autohelp

if [[ -z "$(which nmcli)" ]]; then
	faile 'Required program `nmcli` not found.'
fi

if [[ -z "$*" ]]; then
	printhelp
	exit
fi

WIFICMD="$1" ; shift

if [[ -z "${WIFISAVE+x}" ]]; then
	WIFISAVE="$HOME/.config/wifi.txt"
fi

if [[ ! -f "$WIFISAVE" ]]; then
	mkdir -p "$(dirname "$WIFISAVE")"
	touch "$WIFISAVE"
fi

function savepwd {
	if [[ -z "$(getpwd "$1")" ]]; then
		echo "$1$2" >> "$WIFISAVE"
	else
		sed -r "s/^$1.+$/$1$2/" -i "$WIFISAVE"
	fi
}

function getpwd {
	grep -e "^$1" "$WIFISAVE"|cut -d'' -f2
}

function deletepwd {
	sed -r "/^$1.+$/d" -i "$WIFISAVE"
}

case "$WIFICMD" in
	restart)
		debuge Deactivating wifi
		nmcli radio wifi off

		debuge Re-activating wifi
		nmcli radio wifi on

		infoe Done.
		;;
	stop)
		debuge Deactivating wifi
		nmcli radio wifi off
		infoe Done.
		;;
	start)
		debuge Re-activating wifi
		nmcli radio wifi on
		infoe Done.
		;;
	connect)
		nmcli device wifi rescan
		WIFI_AP="$1"; shift
		WIFI_PW="$1"; shift

		if [[ -z  "$WIFI_AP" ]]; then
			printhelp
			exit
		fi

		if [[ -n "$WIFI_PW" ]]; then
			savepwd "$WIFI_AP" "$WIFI_PW"
			nmcli device wifi connect "$WIFI_AP" password "$WIFI_PW"
		else
			WIFI_PW="$(getpwd "$WIFI_AP")"
			if [[ -n "$WIFI_PW" ]]; then
				nmcli device wifi connect "$WIFI_AP" password "$WIFI_PW"
			else
				nmcli device wifi connect "$WIFI_AP"
			fi
		fi
		;;
	forget)
		deletepwd "$1"; shift
		;;
	list)
		nmcli device wifi rescan
		nmcli device wifi list
		;;
	*)
		faile "Invalid command $WIFICMD"
		;;
esac
